- name: Install Sealed Secrets controller
  ansible.builtin.shell:
    cmd: >
      kubectl apply
      -f https://github.com/bitnami-labs/sealed-secrets/releases/{{ sealed_secrets_version }}/download/controller.yaml
  environment:
    KUBECONFIG: /etc/rancher/k3s/k3s.yaml
  become: true
  changed_when: false

- name: Wait for Sealed Secrets controller to be ready
  ansible.builtin.shell:
    cmd: >
      set -o pipefail &&
      kubectl rollout status deployment/sealed-secrets-controller
      -n {{ sealed_secrets_namespace }}
      --timeout=120s
  environment:
    KUBECONFIG: /etc/rancher/k3s/k3s.yaml
  become: true
  changed_when: false

- name: Fetch Sealed Secrets private cert # noqa: risky-shell-pipe
  ansible.builtin.shell:
    cmd: >
      kubectl get secret
      -n {{ sealed_secrets_namespace }}
      -l sealedsecrets.bitnami.com/sealed-secrets-key=active
      -o jsonpath='{.items[0].data.tls\.crt}'
      | base64 -d
    executable: /bin/bash
  environment:
    KUBECONFIG: /etc/rancher/k3s/k3s.yaml
  become: true
  changed_when: false
  register: sealed_secrets_cert

- name: Save public cert locally
  ansible.builtin.copy:
    content: "{{ sealed_secrets_cert.stdout }}"
    dest: "{{ sealed_secrets_cert_path }}"
    mode: "0644"
  delegate_to: localhost
  become: false
