- name: Create ArgoCD namespace
  ansible.builtin.command:
    cmd: kubectl create namespace {{ argocd_namespace }}
  environment:
    KUBECONFIG: /etc/rancher/k3s/k3s.yaml
  become: true
  failed_when: false
  changed_when: true

- name: Install ArgoCD
  ansible.builtin.shell:
    cmd: >
      kubectl apply -n {{ argocd_namespace }} --server-side
      -f https://raw.githubusercontent.com/argoproj/argo-cd/{{ argocd_version }}/manifests/install.yaml
  environment:
    KUBECONFIG: /etc/rancher/k3s/k3s.yaml
  become: true
  changed_when: false

- name: Wait for ArgoCD server to be ready
  ansible.builtin.shell:
    cmd: >
      kubectl rollout status deployment/argocd-server
      -n {{ argocd_namespace }}
      --timeout=120s
  environment:
    KUBECONFIG: /etc/rancher/k3s/k3s.yaml
  become: true
  changed_when: false
